### ISSUE TITLE
mkdir not working in all cases

### ISSUE THREAD

**Issue by jmozah** [fairDataSociety/fairOS-dfs#10]
**Describe the bug**
mkdir has many possible cases. It is known to not work in all cases

**To Reproduce**
1) - mkdir d1/d2/d3/d4
    - mkdir d1/d2/d5/d6
    - mkdir d1/d2
    - you can only see d5
2) mkdir with root path is not working in all times

**Expected behavior**
- mkdir should work in all cases

**Screenshots**
- None

**Additional context**
- generally, the support for directory operation wiith root is not working.

**Comment by tfius** [comment]
it's invalid in parent directory does not exist, checks are added, parent directories must exists. closing
