### ISSUE TITLE
Cmd cat command doesn't work

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#104]
1 - Run cmd, create pod, upload file 1.txt
2 - Run `cat 1.txt`

Get error: `invalid command`
Expected: stream the file to stdout

**Comment by asabya** [comment]
`cat` command is not availabel in `dfs-cli`

**Comment by tfius** [comment]
@IgorShadurin can you clarify ? should we add cat to cli ?

**Comment by asabya** [comment]
Closing it for now. Feel free to open it, if the issue still persists.
