### ISSUE TITLE
Sometimes pod list is empty

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#111]
1) Login via cmd
2) Call `pod ls`
3) It returns nothing
4) Call `pod ls` second time. It returns actual list of pods

<img width="1467" alt="Screenshot 2021-09-29 at 10 35 56" src="https://user-images.githubusercontent.com/1595061/135223947-1f9c458b-0fe4-41f7-ab52-e06b67b6b953.png">
<img width="1251" alt="Screenshot 2021-09-29 at 10 34 45" src="https://user-images.githubusercontent.com/1595061/135223959-f463c823-4776-4025-9eaa-5d263dfcc240.png">

**Comment by tfius** [comment]
could not reproduce
