### ISSUE TITLE
Upgrading of FairOS to work with bee 1.4.1

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairOS-dfs#113]
**Is your feature request related to a problem? Please describe.**
Currently, FairOS supports/works with Bee version 0.6.2, which is already several versions back from the Bee latest (currently 1.2.0).

**Describe the solution you'd like**
Would like to be able FairOS 0.6.3 to work with Bee version 1.2.0 as backend storage. 

**Describe alternatives you've considered**

**Additional context**
Debugging is needed to check that all the API calls to Bee still work as expected and all the FairOS features are covered. Any changes needed should be done. There should not have been too much differences between bee 0.6.2 and 1.20 so the effort is hopefully routine and minimal.

**Comment by asabya** [comment]
FairOS now works with bee 1.4.1
