### ISSUE TITLE
Add GET endpoint for streaming of files

### ISSUE THREAD

**Issue by mattiaz9** [fairDataSociety/fairOS-dfs#114]
**Is your feature request related to a problem? Please describe.**
Currently the only way to view a file is to download it in advance, which is not good practice for previewing a file.

**Describe the solution you'd like**
The api should expose a GET endpoint for the files so that the browser can utilize the `src` attribute properly for `<image>`, `<video>` and `<audio>` tags.

**Comment by crtahlin** [comment]
I think the current endpoint should actually work with GET, @asabya check with @jmozah before implementing.

**Comment by crtahlin** [comment]
@tfius this is the mentioned issue.

**Comment by tfius** [comment]
ready for testing on testnet

**Comment by crtahlin** [comment]
@mattiaz9 thank you for the issue report.

See above for link to commit or check when merged, issue should be solved - hope this will allow for proper streaming of videos from Fairdrive.
