### ISSUE TITLE
Wrong status code for pod creation

### ISSUE THREAD

**Issue by tomicvladan** [fairDataSociety/fairOS-dfs#117]
**Describe the bug**
When creating a new pod using the endpoint: `POST https://fairos.fairdatasociety.org/v1/pod/new` .

data: `{pod_name: "Consents", password: "..."}`

The pod is successfully created, but the response code is 500 and the response is:

`{"message":"pod new: error uploading data","code":500}`

The status code should be 200.

**Comment by tfius** [comment]
please follow standard return codes as in ie.
- https://umbraco.com/knowledge-base/http-status-codes/ 
- https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
