### ISSUE TITLE
Move userName -> address mapping to Swarm and make dfs 100% stateless

### ISSUE THREAD

**Issue by jmozah** [fairDataSociety/fairOS-dfs#12]
**Is your feature request related to a problem? Please describe.**
To move the `userName` -> `address` mapping in Swarm and make dfs 100% stateless.

**Describe the solution you'd like**
- A simple KV store to host a indexed keys and values
- Explore Key-Value format or Sequence file format of HDFS

**Describe alternatives you've considered**
- None

**Additional context**
- https://cwiki.apache.org/confluence/display/HADOOP2/SequenceFile

**Comment by asabya** [comment]
#187 introduces a solution for storing username -> address mapping in ens registry

**Comment by asabya** [comment]
Released in [v0.8.0](https://github.com/fairDataSociety/fairOS-dfs/releases/tag/v0.8.0)
