### ISSUE TITLE
Error when creating a pod which was previously deleted

### ISSUE THREAD

**Issue by tomicvladan** [fairDataSociety/fairOS-dfs#124]
**Describe the bug**
When this endpoint `POST https://fairos.fairdatasociety.org/v1/pod/new` is called for a pod which was previously deleted, the response is:

`{"message":"pod new: error uploading data","code":500}`

**Comment by asabya** [comment]
This should be gone once #118 is resolved

**Comment by asabya** [comment]
duplicate of #117
