### ISSUE TITLE
Cannot download an existing file

### ISSUE THREAD

**Issue by tomicvladan** [fairDataSociety/fairOS-dfs#125]
**Describe the bug**
When trying to download a file which already exists using this endpoint `GET https://fairos.fairdatasociety.org/v1/file/download?file_path=/reactjs.org/filename.json&pod_name=Podname` the response is:

`{"message":"download: file not present","code":500}`

**Comment by tfius** [comment]
can't reproduce

**Comment by asabya** [comment]
closing this for now
