### ISSUE TITLE
CLI prompt window isn't possible to scroll

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#126]
**Describe the bug**
CLI prompt window isn't scrollable

**To Reproduce**
1. Start `dfs-cli`
2. Type `k`
4. See kv related commands in prompt window. In right side you can see scroll bar which doesn't work

**Expected behavior**
Scroll bar should work or command list should be displayed without scrollbar window

**Screenshots**
<img width="574" alt="Screenshot 2021-11-01 at 14 19 14" src="https://user-images.githubusercontent.com/1595061/139665617-c16ead2b-f5eb-49b2-894b-853510a8d356.png">

**Comment by asabya** [comment]
We can scroll using "Tab"
