### ISSUE TITLE
/kv/entry/get does not return right value

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairOS-dfs#138]
**Describe the bug**
/kv/entry/get is returning some other value for a given key

```
// /kv/entry/put
{
"pod_name": "pod1000",
"table_name": "tea_table2",
"key": "key1",
"value": "sawaan"
}
```

```
// /kv/entry/get?pod_name=pod1000&table_name=tea_table2&key=key1
{
    "keys": [
        "key1"
    ],
    "values": "c2F3YWFu"
}
```

**Comment by asabya** [comment]
Well it sends the actual value but in `[]byte`  format, but sending `[]byte` in a json isn't a good idea as json deals with data only in text format. May be returning the string of `[]byte` will be a good idea.

**Comment by tfius** [comment]
can you encode to string with base64 ?

**Comment by tfius** [comment]
this introduces breaking change to ecosystem

**Comment by tfius** [comment]
@IgorShadurin what do you think ?

**Comment by IgorShadurin** [comment]
I used this method in a Galileo project and I don't like the fact that the response is returned in base64. 
If I store a string as a value, then it is forcibly converted to base64, which increases the amount of traffic and puts a load on the client side for regular decoding.
Perhaps this method should receive an additional parameter like "output_format", depending on which the value will be displayed in a different form. For example, with output_format=bytes, only the raw value in bytes will be displayed, with output_format=text, the textual form of information will be displayed, with output_format=base64, respectively. 
Perhaps this method can be left as is, but add a new entry/download method to avoid json limitation and that will do what I described above.

**Comment by asabya** [comment]
> can you encode to string with base64 ?

So this is returning base64-encoded string automatically from go itself.

**Comment by asabya** [comment]
> I used this method in a Galileo project and I don't like the fact that the response is returned in base64. If I store a string as a value, then it is forcibly converted to base64, which increases the amount of traffic and puts a load on the client side for regular decoding. Perhaps this method should receive an additional parameter like "output_format", depending on which the value will be displayed in a different form. For example, with output_format=bytes, only the raw value in bytes will be displayed, with output_format=text, the textual form of information will be displayed, with output_format=base64, respectively. Perhaps this method can be left as is, but add a new entry/download method to avoid json limitation and that will do what I described above.

JSON is a text format and does not support byte array. So `output_format=bytes` will not work I guess.

go json package converts []byte to base64-encoded string itself
`Array and slice values encode as JSON arrays, except that []byte encodes as a base64-encoded string, and a nil slice encodes as the null JSON value.`

**Comment by asabya** [comment]
Duplicate of #93

**Comment by tfius** [comment]
well if bytes will contain invalid characters, json will be invalid and not readable. I think bytes[] should be base encoded for correctness and robustness. @IgorShadurin, we can add another method to api that will do this by default, and we keep the old method that sends bytes but will always fail if bytes contain invalid characters.

**Comment by IgorShadurin** [comment]
New method would be great

**Comment by asabya** [comment]
`/kv/entry/get-data` will be added with a `format` flag. `format` can be `string` or `byte-string`
