### ISSUE TITLE
Cookie is returning fairos.io only domain

### ISSUE THREAD

**Issue by wendydv1989** [fairDataSociety/fairOS-dfs#14]
**Describe the bug**
The cookie used to authenticate / session manage is set at fairos.io

**To Reproduce**
Login or signup, check console/xhr and see the contents of the cookie

**Expected behavior**
A cookie that's being set for *.fairdrive.io

**Comment by jmozah** [comment]
Added a falg to add the domain to be returned --cookieDomain
