### ISSUE TITLE
Check validity of  postageBlockId

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairOS-dfs#157]
**Describe the bug**
Currently server will start with any string passed as postageBlockId. May be we can add a validity check for it.

**Comment by IgorShadurin** [comment]
Perhaps it is possible to get rid of this parameter and get stamps automatically/manually from the existing ones (this is implemented in swarm-cli, for example) or create them.

**Comment by asabya** [comment]
That makes much more sense. We can check for available stamps and use any one.

**Comment by asabya** [comment]
stampkeeper will be used to manage stamp.
