### ISSUE TITLE
Add file append support (WAL)

### ISSUE THREAD

**Issue by jmozah** [fairDataSociety/fairOS-dfs#16]
**Is your feature request related to a problem? Please describe.**
Add feature to append data to a file

**Describe the solution you'd like**
For building Data bases, a Write Ahead Log (WAL) is an essential piece of data stucture.
To realize this we need to have files which have append support.

**Comment by jmozah** [comment]
@tfius  we need to discuss this
1) create a ever growing file with some closing limits
2) closing limits can be close the file every hour and name in a directory structure like this YYYY/MM/DD/HH.csv
3) closing limitt can also be file size ( like close the file when it reaches 100GB
4) when i say close.. it will be available as a seperate file and you can start working on it....
5) even if you say close size is 100GB, at every 64Mb, the data will be flushed to Swarm for persistance.. so no worr

**Comment by tfius** [comment]
imagine having a bunch of sensors writing small amounts of data to it, but high frequency

**Comment by tfius** [comment]
and you need latest data as soon as possible
