### ISSUE TITLE
Can't check if exists kv entry without downloading it

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#167]
In some cases required to check if kv entry is already exists. As I can see in current state it's possible to check only with `kv/entry/get` method.

It would be great to implement something like
`kv/entry/exists` which will return true/false as an answer.

**Comment by tfius** [comment]
if get fails, return should be meaningful, another endpoint would add additional complexity just for checking. I would go for an endpoint that would return an iterator or an array of possible keys so one could iterate through
