### ISSUE TITLE
Examples in the API docs should use https

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairOS-dfs#168]
**Describe the bug**
Currently, examples are done for http.

**To Reproduce**
See : https://docs.fairos.fairdatasociety.org/api/

**Expected behavior**
https (secure http) should be displayed by deafult.

**Screenshots**

![image](https://user-images.githubusercontent.com/1554520/146765589-360520b0-6bf5-4ee1-8195-746adcf0f648.png)

**Additional context**

**Comment by tfius** [comment]
localhost won't work on https unless user sets certs
