### ISSUE TITLE
Unable to create file with the same name after deletion

### ISSUE THREAD

**Issue by salmanff** [fairDataSociety/fairOS-dfs#169]
After deleting a file, if you upload a new file with the same name as the deleted one, you get this response:
{
    "Responses": [
        {
            "file_name": "file_to_upload.png",
            "message": "error uploading data"
        }
    ]
}

**To Reproduce**
1. "/file/upload": Upload a file 
2. "/file/delete": Delete the file 
3. "/file/upload": Upload a file with the same name as the one in step 1 and  2 

**Expected behavior**
Should be able to upload a file with the same name after deleting the original
Note that this seems similar to the resolved issue 139 (https://github.com/fairDataSociety/fairOS-dfs/issues/139) which relates to "docs/new".

**Comment by asabya** [comment]
I can upload a file having a previously deleted file name.
![image](https://user-images.githubusercontent.com/15252513/146916784-809fe27c-71dd-4587-811d-5a57b7afc82b.png)


Can you please confirm which version you are using?

**Comment by salmanff** [comment]
thanks. v1. (eg https://fairos.fairdatasociety.org/v1/file/upload)

**Comment by asabya** [comment]
This is an old endpoint. You can use [this](https://fairos-mainnet.fairdatasociety.org/v1/file/upload) endpoint instead. 

This issue is fixed in the latest release. closing this.
