### ISSUE TITLE
Documenting / detailing error messages

### ISSUE THREAD

**Issue by salmanff** [fairDataSociety/fairOS-dfs#184]
It would be great to (1) have better documentation on error message and / or (2) give more details on them .. ie
1. What do these errors mean:
- no feed updates found
- payload is greater than 4096
2. It would be great to have more details returned on reasons for failure for this:
- error uploading data

**Comment by crtahlin** [comment]
@tfius please check and prioritize.

**Comment by tfius** [comment]
More clear messages would help developers
- Feed does not exist or was not updated yet.
- Payload size is too large. Maximum payload for feed is 4096 bytes.  
for 2.
- must discuss with @asabya, to many potential causes for this error

**Comment by asabya** [comment]
- "no feed updates found" : this seems self explanatory to me. May be we can remove the "feed", just say "requested resource not found"
- Any info on what caused "payload is greater than 4096"? @salmanff. As @tfius said while creating a feed, the payload should be less than 4096.

- On many cases we just forward what bee sends us, we don't get much info on such cases. "error uploading data" is one of them. We can improve this by saying which request caused this.

**Comment by tfius** [comment]
Agreed, self explanatory if dev has insight how feeds work and has knowledge about limitations. We should add bit more explanatory information, like in my first comment. 

2. lets add information about failed request.

**Comment by salmanff** [comment]
Hi - thx and sorry for late response.
"no feed updates found" moved to discord discussion. But I understand it, even if the "Schrodinger's directories" issue remains.
On "payload is greater than 4096". This error also seems to be triggered when two write operations take place in quick sequence. So I dont think it only relates to the payload of one API call. Interestingly, it looks like the operation is finalised successfully even when the error is issued (which is why it took me forever to figure out what was going on.) ie It doesnt look like there is an error, despite the error message.
This extract of my log may explain:
**First Write to filename: rec-557-1644056305149.adb**
```
  writeOptions: {
    hostname: [REMOVED]
    path: '/v1/file/upload',
    method: 'POST',
    headers: { [REMOVED]}
  },
  contents: '{"age":5,"_id":"jYKj9di3IP5Wq6by"}\n'
}
```
Returns: 
```
'{"Responses":[{"file_name":"rec-557-1644056305149.adb","message":"uploaded successfully"}]}\n' +  '\n'
```

**Immediately afterwards, Second Write to file name: rec-581-1644056311362.adb :**
```
writeOptions: {
    hostname: [REMOVED],
    path: '/v1/file/upload',
    method: 'POST',
    headers: {[REMOVED] }
  },
  contents: '{"age":57,"_id":"wAgMM1OvLJX8D1FZ"}\n'
}
```
Returns 
`'{"Responses":[{"file_name":"rec-581-1644056311362.adb","message":"modify dir entry : payload is greater than 4096"}]}\n' `

However, when you read the same file, it has been written. Reading it results in:
`{ err: null, returns: '{"age":57,"_id":"wAgMM1OvLJX8D1FZ"}\n' }`

Perhaps this is not a documentation issue.. but more fundamental about when a payload error should be sent at the swarm level.

**Comment by crtahlin** [comment]
@tfius , is this implemented / solved?

**Comment by crtahlin** [comment]
@tfius what is the status?

**Comment by asabya** [comment]
@crtahlin There has been few improvements regarding these kind of messages in #186
