### ISSUE TITLE
Incorrect swarm-encrypt header

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#198]
I looked at the code base of the project and found this line. It contains an invalid encryption header for bee. This piece of code is used to upload blocks of files.

Currently, these blocks are uploaded without encryption, which can lead to the disclosure of the contents of the files.

https://github.com/fairDataSociety/fairOS-dfs/blob/ab15d5aa2ee8b990a217416ce2f79dfc13302b92/pkg/blockstore/bee/client.go#L52

The correct value is `swarm-encrypt`

**Comment by asabya** [comment]
@IgorShadurin, @crtahlin This is fixed in this commit [eef257b1976a7e31831d474dd33b76141a33a5e7](https://github.com/fairDataSociety/fairOS-dfs/pull/187/commits/eef257b1976a7e31831d474dd33b76141a33a5e7)
