### ISSUE TITLE
FairOS is not working on testnet

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairOS-dfs#209]
Which is a blocker for testing the login flow for Fairdrive.

**Comment by crtahlin** [comment]
@molekilla please check and update status.

**Comment by molekilla** [comment]
I didn't document this last time, DevOps had to update the docker but I don't know if it was deployed at all. But we better plan with devops releasing theapp with `fdp-storage` v0.4.0 now that is more stable than previous versions. Let me know.

**Comment by molekilla** [comment]
current master btw , to load the fairos environment use `docker compose up`

**Comment by crtahlin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fairdrive-6266aaec4367e80011e0c3c5/issues/fairDataSociety/fairOS-dfs/209?planning-poker) with ZenHub @molekilla @tfius

**Comment by crtahlin** [comment]
As Fairdrive on testnet now uses fdp-storage, this is no longer relevant from that respect.
