### ISSUE TITLE
Storing user address on file uploading

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#212]
When saving meta information about a file (when uploading a file), there is a "user_address" field in which the user's address is stored. After serialization, it was converted from a binary representation to a set of numbers. In some other places, the address is stored in hex form.

I think for unification it would be better to save this address everywhere in hex form without 0x.

**Comment by asabya** [comment]
it is bytes representation of user address. 

The suggestion is good but, changing that will break compatibility with the files already in the network. 

how is fdp-storage storing it? @IgorShadurin

**Comment by asabya** [comment]
`user_address` was removed in bad5f1ca48985494ea7062cef3606afb8c0a1984
