### ISSUE TITLE
Wasm support for dfs

### ISSUE THREAD

**Issue by jmozah** [fairDataSociety/fairOS-dfs#23]
**Is your feature request related to a problem? Please describe.**
- compile dfs in wasm

**Describe the solution you'd like**
- exposrt it as a wasm module so that it can be imported in any JS implementation

**Describe alternatives you've considered**
- None

**Additional context**
- None

**Comment by asabya** [comment]
from [v0.9.2](https://github.com/fairDataSociety/fairOS-dfs/releases/tag/v0.9.2) we have su[port for wasm
