### ISSUE TITLE
Informations shown in api root is useless 

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairOS-dfs#244]
If we go to api root endpoint we currently see information about the fairOS node
```
FairOS-dfs
dev
http://localhost:1663
trace
:9090
:9091
localhost
[http://localhost:3000 http://localhost:8081]
```

We don't need to show all these. This endpoint can only be used for checking if we can connect with with the fairOS-dfs server.
So a 200 response code with "OK" as body will be enough for this endpoint.

@crtahlin @tfius @darkobas2

**Comment by darkobas2** [comment]
agree
