### ISSUE TITLE
Can't retrieve file's content uploaded during active session

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#278]
**Describe the bug**
Unable to download a file that was uploaded during an active FairOS session.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create FairOS account (FairOS instance1)
2. Create pod1
3. Upload file1 to pod1
4. Using the same credentials - login to other instance (instance2) of FairOS or fdp-storage
5. Upload file2 to pod1 using instance2
6. Try to download file2 using instance1
7. Get error about uploading error

Try to close and open pod, then file2 could be downloaded.

**Expected behavior**
File2 should downloaded without pod re-opening.

**Comment by asabya** [comment]
This is expected behavior as we cache the folder and file entries in fairOS-dfs.
Previously there was only one way to recache, pod-sync. Added dir/ls also with #372. 

So to download a file uploaded from a different instance we either have to call pod-sync or dir/ls.
