### ISSUE TITLE
feed test is having issues in race tests in CI

### ISSUE THREAD

**Issue by jmozah** [fairDataSociety/fairOS-dfs#3]
**Describe the bug**
- CI fails in the ubuntu build in race-tests. The `update-feed` test fails with the following 

**To Reproduce**
- Cannot reproduce consistently. It randomly fails the CI

**Expected behavior**
- The test should pass in race-test ALWAYS

**Screenshots**
```
update 83 Done
update 84 Done
update 85 Done
update 86 Done
##[error] feed_test.go:105:
--- FAIL: TestFeed (4.34s)
--- PASS: TestFeed/create-feed (0.03s)
--- PASS: TestFeed/read-feed-first-time (0.00s)
--- FAIL: TestFeed/update-feed (3.50s)
FAIL
FAIL github.com/jmozah/intOS-dfs/pkg/feed 4.389s
=== RUN TestMarshallers
--- PASS: TestMarshallers (0.00s)
```

**Additional context**
- None

**Comment by AngelaVitzthum** [comment]
Need to verify if this issue still persists.

**Comment by crtahlin** [comment]
This is surely solved by now, so closing.
