### ISSUE TITLE
Minimum blockSize for upload

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairOS-dfs#315]
**Is your feature request related to a problem? Please describe.**
Currently we do not have a lower limit of setting a `blockSize`. If any upload request is made with blockSize really low with a big file size. the underlying bee could be clogged with a ton of requests.   

**Describe the solution you'd like**
We set the minimum blockSize to "1Mb"

**Comment by crtahlin** [comment]
IMO, go with your suggestion, but leave the option to change later. The important thing is to have the rationale documented (e.g. in this issue), so that it can be reevaluated later.

**Comment by nugaon** [comment]
the minimum blocksize should be then 4KB since that is the smallest unit in Swarm

**Comment by asabya** [comment]
> the minimum blocksize should be then 4KB since that is the smallest unit in Swarm

This will be too low. 

e.g. For a 32 mb file (32768 kb) it will be 8192 (32768/4) requests to the underlying bee.

**Comment by nugaon** [comment]
I've seen applications that only use chunk endpoint to upload big files for which they not only upload the datachunks but the intermediate chunks as well. 
all requests shouldn't happen at once, instead the requests should be divided into smaller groups that the Bee node still can handle.

**Comment by asabya** [comment]
@nugaon I tried another approach in #379 not the one you suggested. But it seems that both the cases will increase the upload time. 

So we should opt for a minimum block size limit for now IMHO. It will make fairos-dfs upload faster than direct uploads used by other applications.
