### ISSUE TITLE
Regex support for document store

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairOS-dfs#360]
**Is your feature request related to a problem? Please describe.**
Currently we have document store works lexicographically, i.e. if we have "Alice", "John", "Johna", "Zuri" in a store and we try to find similar names starting with "John". We will get 3 results "John",  "Johna", "Zuri". That is because we have to pass the expression as "name=>John" and being lexicographic "Zuri" is > "John". 

This is confusing to the user and logically wrong in most cases using document store.

**Describe the solution you'd like**
We can use regex in case of string. So to the user expression stays the same, So we query  "name=>John" and get back only two entries. We can also add wild card regex "name=>John." for searching "Johna" .

**Comment by tfius** [comment]
This is great.  We should add this to documentation.
