### ISSUE TITLE
Convert bytes upload into chunks

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairOS-dfs#379]
**Is your feature request related to a problem? Please describe.**
We use the bytes api to upload file content. 

I guess this is the default behaviour. But this creates the following issue on bee side :- We break the file into user defined blocks. if the block size is too low, say 4kb, the it will cause a ridiculous number of requests for a 1gb file. 

**Describe the solution you'd like**
As per my understanding, bee does the following thing on bytes api,

- bee handles bytes.
- breaks them in chunks
- upload the chunks
- return the "sum" address for the bytes

May be, we can do the same on fairos side also. So the proposed solution is

- We handle the bytes
- break that into chunks
- use chunk stream websocket connection to upload them
- generate the sum address.

**Describe alternatives you've considered**
We can restrict the block size to not be extremely low. proposed [here](https://github.com/fairDataSociety/fairOS-dfs/issues/315)
**Additional context**
This will reduce the load on bee, also increase performance.

**Comment by asabya** [comment]
The proposed solution works fine, but the upload time doubles.

### 5 Mb file upload on a local bee 
- takes 1.2s on average on `/bytes` api
- takes 2.3s on average on `/chunks/stream` 

### 100 Mb file upload on a local bee
- takes 22.2s on average on `/bytes` api
- takes 47s on average on `/chunks/stream` 

so it almost doubles 

So, may be we opt for #315 for now, and set a minimum block size.

**Comment by IgorShadurin** [comment]
My calculations are:

5 (mb) / 1.2 (s) = 4.16 (mb per second)
100 (mb) / 22.2 (s) = 4.5 (mb per second)

How was the calculation due to which there was a slowdown by 2 times?

**Comment by asabya** [comment]
Out of scope. Closing it for now.
