### ISSUE TITLE
missing docs - allowed index types and simple index string `si` format in payloads

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairOS-dfs#393]
Simple Index `si` used in some of `/v1/doc/*` endpoints requires some documentation and explanation: 
- possible formats for keys and values
- default index key `id` must be string
- allowed index types (seems `bool` is a valid value type but not a valid indexType)

![image](https://user-images.githubusercontent.com/520570/211319442-d2452eba-f4c0-436c-b876-43d3b9990a5f.png)
![image](https://user-images.githubusercontent.com/520570/211318877-89c0ffa9-909d-47f6-9c05-81e544a70d37.png)

**Comment by asabya** [comment]
explained in doc
![image](https://user-images.githubusercontent.com/15252513/211476450-b959d4cd-3d73-4d4f-8973-40c79fe75af9.png)
