### ISSUE TITLE
missing docs - `expr` string parameter in `/v1/doc/find`

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairOS-dfs#394]
from the documentation it is unclear what format of search expressions are supported in this string parameter

![image](https://user-images.githubusercontent.com/520570/211319734-9824ecd3-15e9-437d-8839-cc66744905a0.png)

**Comment by rampall** [comment]
- allowed operators in `expr` are `=`, `>`, `>=`, `<=`, `<`
expr is required but it is unclear how to set `!=` or match any / include all `*`

**Comment by asabya** [comment]
explained in the docs
![image](https://user-images.githubusercontent.com/15252513/211476123-452e845f-d8c5-4316-91be-3cefc656d724.png)
