### ISSUE TITLE
response from `/v1/doc/find` 

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairOS-dfs#396]
-  `/v1/doc/find`  returns an array of integers according to docs (but it actually returns an array of Base64 strings) :

![image](https://user-images.githubusercontent.com/520570/211427776-21c6ee52-85d8-4973-bdf4-c961395de8e9.png)
![image](https://user-images.githubusercontent.com/520570/211427168-b585e293-a9f0-42ac-b4c0-8a10851cc29a.png)
![image](https://user-images.githubusercontent.com/520570/211428110-43c851c4-455e-458f-af6d-d8c92eb2decc.png)

**Comment by asabya** [comment]
fixed in the docs 
![image](https://user-images.githubusercontent.com/15252513/211475903-60411dc5-d99b-4c17-8408-a557d52f2907.png)
