### ISSUE TITLE
unclear error message - `could not create new Manifest` on `/v1/doc/entry/put` endpoint

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairOS-dfs#397]
it;s unclear what this means for the developer - or how he/she can fix this?
![image](https://user-images.githubusercontent.com/520570/211431536-7717cfe0-55fa-4ea0-a70a-6d0ccaf2c953.png)

**Comment by asabya** [comment]
@rampall, can you please provide the steps to reproduce this?

**Comment by rampall** [comment]
> @rampall, can you please provide the steps to reproduce this?

@asabya  Couldnt recreate this exact scenario. So closing this for now.
