### ISSUE TITLE
doc endpoint `/v1/doc/entry/delete` throws 404

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairOS-dfs#398]
doc endpoint `/v1/doc/entry/delete` throws 404:

![image](https://user-images.githubusercontent.com/520570/211433224-f492ab71-4275-416d-ad6e-4a7280069dc7.png)

other endpoints seem to be working fine like `/v1/doc/open`:

![image](https://user-images.githubusercontent.com/520570/211433451-92ced163-4edf-4fce-8a57-51fe06f0b59d.png)

**Comment by asabya** [comment]
@rampall Thanks for the issue.

fixed in the docs: https://docs.fairos.fairdatasociety.org/api/index.html#tag/doc/paths/~1v1~1doc~1entry~1del/delete
