### ISSUE TITLE
Lookup test failure in CI

### ISSUE THREAD

**Issue by jmozah** [fairDataSociety/fairOS-dfs#4]
**Describe the bug**
- Feed lookup takes longer than expected sometimes

**To Reproduce**
- Could not reproduce consistently. Happens randomly sometimes

**Expected behavior**
- The feed tests should pass ALWAYS

**Screenshots**
```
##[error] lookup_test.go:492: Expected lookup to complete faster than 379.237699ms since we provided a hint. Took 573.726385ms
=== RUN TestSparseUpdates/LongEarth
```

**Additional context**
- None

**Comment by AngelaVitzthum** [comment]
Need confirmation as to if this is still an issue.

**Comment by crtahlin** [comment]
Surely solved, closing.
