### ISSUE TITLE
Unable to create table with same name of a deleted table `/doc/new`

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairOS-dfs#433]
**Describe the bug**
`/doc/new` returns

```
{
    "message": "doc create: index already present",
    "code": 500
}
```
**To Reproduce**
1. Create new table
2. Delete the table
3. Try to create table with the same name

**Comment by asabya** [comment]
![doc](https://user-images.githubusercontent.com/15252513/229067043-f6cd6d1a-abe8-48fb-a63a-8d8fbea2a228.gif)

Failed to reproduce. Closing it for now. Please feel free to re-open it if the issue still persists.
