### ISSUE TITLE
`/doc/put` throws 500 error (even though it works)

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairOS-dfs#435]
`/doc/put` throws 500 error (even though the data is updated)

![image](https://user-images.githubusercontent.com/520570/222979892-5ebc1236-1c87-4d4b-9d22-8ff36a7b9fa7.png)
---
![image](https://user-images.githubusercontent.com/520570/222979915-034f3fd8-ba76-4fcf-913b-e0866b2308b1.png)
---
![image](https://user-images.githubusercontent.com/520570/222980007-92450e73-377d-4110-b977-24ce4a29718f.png)

**Comment by asabya** [comment]
Failed to reproduce with v0.9.3. Closing it for now. Please feel free to re-open it if the issue still persists.
