### ISSUE TITLE
Removing encryption of shared metadata

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#437]
If we want to share a file with `file/share` api method, then the file metadata is encrypted using secp256k1 (this algorithm is different from the one we use to encrypt the feed data), and then the encrypted data is uploaded using the encrypted bee api.

The final share reference is 128 characters encrypted reference + 10 characters unix timestamp with which encryption occurs. There are 138 characters in total.

It seems to me that encrypting this metadata with secp256k1 is redundant and can be removed because the bee itself encrypts the data.
Or we can use the same algorithm that we use to upload encrypted data to the feed.

Do we need this additional encryption and this particular algorithm?

**Comment by asabya** [comment]
We don't need it IMO. Removing it
