### ISSUE TITLE
[dfs-cli] Spaced input not working

### ISSUE THREAD

**Issue by jmozah** [fairDataSociety/fairOS-dfs#45]
**Describe the bug**
dfs-cli is not taking spaced input .
Ex: user contact 435678 9940657738 "Door No 1, west street" Ljublianana "Ljubliana State" 600013

In  the above example, "Door no 1, west street" should be taken as one line... but it is taking as multiple input.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tfius** [comment]
also #24
