### ISSUE TITLE
Schema errors with OpenAPI documents

### ISSUE THREAD

**Issue by tmm360** [fairDataSociety/fairOS-dfs#50]
**Describe the bug**

Open API documents into `/openapi` directory report several schema errors with common validator tools. An example of these is https://editor.swagger.io/.

With errors it's difficult to use API documentation with OpenAPI realated tools.

EDIT: same also for downloadable documentation at https://fairos.io/bzz/fairos.eth/api/

**Expected behavior**

OpenAPI specifications should not have schema issues.

**Comment by tmm360** [comment]
I'm also having issues with internal file `$ref` composition with documentation at https://fairos.io/bzz/fairos.eth/api/.

This is an example of received error from tool:
```
Could not resolve the path '#/paths/~1user~1login/post/requestBody/content/application~1x-www-form-urlencoded/schema/properties/user'.
```

I'm trying to manually fix the schema, but I'm not able to solve these references, even if this documentation is generated with a single file.

For context, I'm using [NSwagStudio](https://github.com/RicoSuter/NSwag/wiki/NSwagStudio) trying to generate a client.

**Comment by tmm360** [comment]
There are also semantic errors, very often is used `"requestBody"` for parameters that should be passed in query. Also with `GET` and `DELETE` calls that can't have a body by specifications.

**Comment by tfius** [comment]
hi, check this https://github.com/fairDataSociety/fairOS-dfs/issues/526
