### ISSUE TITLE
Use a single OpenAPI documentation file

### ISSUE THREAD

**Issue by tmm360** [fairDataSociety/fairOS-dfs#51]
**Describe the problem**

Currently OpenAPI documentation at `openapi/` is splitted into two files: `dfs.yaml` and `dfs-common.yaml`. This is a source of complications because several tools accept single files at once, and can't resolve `$ref` to external files.

I'm receiving errors from tools that say that `$ref` paths can't be resolved.

**Describe the solution you'd like**

I think that could be easier, at this stage, to keep definition unified, and maybe return to split common definition only when this could be useful for share data with different API set.

**Comment by asabya** [comment]
As there is no `dfs-common.yaml` available right now. I suppose this is irrelevant.
