### ISSUE TITLE
Invalid domain in "set-cookie" header

### ISSUE THREAD

**Issue by tmm360** [fairDataSociety/fairOS-dfs#52]
**Describe the bug**
Trying to login, a `Set-Cookie` header is returned. Here an example:

`Set-Cookie: fairOS-dfs=MTYxMzA1Njk2OXxGNGRlQl9rVFBoYjlDUXNBOW52UUZZaEtiMVgzRXh2U19INGNrNGpILWVhazhRNndTeGw5T1llT1pYUEJ6a3MxMmxfWTN5Q0Npb2xkMElIOEVhb3VHb3FCZ2VvVlVvUGI5ejVHOXcyc3hERVo3ZUo0TzlvWXUtU3E1WGZvSVFkTllWZ0lVa0ZKX3lmRExfTHpMTXRpVkUza0djR1BPOTRwcXdnaGJBPT18VAdqYuWHWCDFevwZfhJt7wAL6QHsoHPrtBDaIkirwlo=; Path=/; Domain=api.fairos.io; Expires=Fri, 12 Feb 2021 15:22:49 GMT; HttpOnly; Secure; SameSite=None`

This header reports `Domain=api.fairos.io` even if for example it's locally executed at `http://localhost:9090/`. This is an invalid declaration, and any client with an active security controls will discard this set-cookie instruction.

**To Reproduce**
1. Try to login
2. Inspect the response

**Expected behavior**
The Domain restriction, if reported, should be taken from the destination domain into the request.

**Comment by Xerosigma** [comment]
I'm seeing this as well! Currently can't maintain authenticated state. Do you have any work around you're working with by any chance?

**Comment by Xerosigma** [comment]
Changing it to local didn't work, I believe the issue is due to the following:

```
Adding the Secure parameter makes sure the cookie can only be transmitted securely over HTTPS, and it will not be sent over unencrypted HTTP connections:
```

**Comment by Xerosigma** [comment]
So turns out **SameSite** & **Secure** are what seems to be contributing to the problem.
https://github.com/fairDataSociety/fairOS-dfs/blob/d830de5b3d609f6ba87a2266eadbbe548027879a/pkg/cookie/cookie.go#L70

I updated the conditional statements to include consideration for `cookieDomain == "localhost"` and I was able to get the cookie.

```
if cookieDomain == "localhost" {
		cookie = &http.Cookie{
			Name:     CookieName,
			Value:    encoded,
			Path:     "/",
			Expires:  expire,
			HttpOnly: true,
			MaxAge:   0, // to make sure that the browser does not persist it in disk
		}
	} else if cookieDomain == "" {
		cookie = &http.Cookie{
			Name:     CookieName,
			Value:    encoded,
			Path:     "/",
			Expires:  expire,
			HttpOnly: true,
			SameSite: http.SameSiteNoneMode,
			Secure:   true,
			MaxAge:   0, // to make sure that the browser does not persist it in disk
		}
	} else {
		cookie = &http.Cookie{
			Name:     CookieName,
			Value:    encoded,
			Path:     "/",
			Expires:  expire,
			HttpOnly: true,
			Domain:   cookieDomain,
			SameSite: http.SameSiteNoneMode,
			Secure:   true,
			MaxAge:   0, // to make sure that the browser does not persist it in disk
		}
	}
```
