### ISSUE TITLE
OpenAPI specs are wrong and with errors

### ISSUE THREAD

**Issue by tfius** [fairDataSociety/fairOS-dfs#526]
```
Semantic error at paths./public/{ref}/{file}
Declared path parameter "ref" needs to be defined as a path parameter at either the path or operation level
Jump to line 135
Semantic error at paths./public/{ref}/{file}
Declared path parameter "file" needs to be defined as a path parameter at either the path or operation level
Jump to line 135
Semantic error at paths./v1/dir/rmdir.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 389
Semantic error at paths./v1/doc/delete.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 516
Semantic error at paths./v1/file/delete.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 1014
Semantic error at paths./v1/kv/delete.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 1590
Semantic error at paths./v1/kv/entry/del.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 1631
Semantic error at paths./v1/pod/delete.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 2225
Structural error at paths./v1/user/delete.post
should have required property 'responses'
missingProperty: responses
Jump to line 2776
Structural error at paths./v1/user/export.post
should have required property 'responses'
missingProperty: responses
Jump to line 2781
Structural error at paths./v1/user/login.post
should have required property 'responses'
missingProperty: responses
Jump to line 2813
Structural error at paths./v1/user/present.get
should have required property 'responses'
missingProperty: responses
Jump to line 2851
Structural error at paths./v1/user/signup.post
should have required property 'responses'
missingProperty: responses
Jump to line 2856
Semantic error at paths./v2/user/delete.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 2907
```

**Comment by tfius** [comment]
Errors in issue are from yaml converted to JSON https://docs.fairos.fairdatasociety.org/api/index.html (where button points to blob) it would be nice to have direct access to yaml and json files for specs.

 
Semantic error at paths./public/{ref}/{file}
Declared path parameter "ref" needs to be defined as a path parameter at either the path or operation level
Jump to line 603
Semantic error at paths./public/{ref}/{file}
Declared path parameter "file" needs to be defined as a path parameter at either the path or operation level
Jump to line 603
Structural error at paths./v1/file/upload.post.parameters.2
should NOT have additional properties
additionalProperty: example
Jump to line 1812
Structural error at paths./v1/file/upload.post.parameters.4
should NOT have additional properties
additionalProperty: example
Jump to line 1823
Structural error at paths./v1/file/upload.post.parameters.6
should NOT have additional properties
additionalProperty: example
Jump to line 1833
Structural error at paths./v1/kv/entry/get-data.get.parameters.3
should NOT have additional properties
additionalProperty: example
Jump to line 2034
Structural error at paths./v1/user/delete.post.responses
should define at least one response
Jump to line 2963
Structural error at paths./v1/user/export.post.responses
should define at least one response
Jump to line 2969
Structural error at paths./v1/user/login.post.responses
should define at least one response
Jump to line 3001
Structural error at paths./v1/user/present.get.responses
should define at least one response
Jump to line 3035
Structural error at paths./v1/user/signup.post.responses
should define at least one response
Jump to line 3041

**Comment by tfius** [comment]
also added go, python, c# generated libraries to latest release @asabya

**Comment by asabya** [comment]
> [swagger.yaml.txt](https://github.com/fairDataSociety/fairOS-dfs/files/12051471/swagger.yaml.txt) here is updated yaml

```
      deprecated: true
      responses: 
        "200":
          description: OK
```

I don't think these changes are required as the apis are deprecated.

Also 
```
- description: format of the value example byte-string, string
```

this already has the examples is a separate key
```
example: byte-string, string
```

Fixed the public api endpoint. things should be good now
