### ISSUE TITLE
Asterisk character is not handled in CLI

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairOS-dfs#527]
**Describe the bug**
Using the asterisk "*" character as a wildcard seems is not supported with uploadDir, see screenshot. 

Some errors/messages are returned that seem like nothing was imported (or "." was imported multiple times, whatever that means).  

**To Reproduce**
See screenshot. The folder contains subfolders.

**Expected behavior**
Either subfolders should be uploaded, or an error returned and operation aborted. 
Also, there seems to be no way to cancel the operation (CTRL-C does not work). Some way to cancel operations should be available in general.

**Screenshots**

![image](https://github.com/fairDataSociety/fairOS-dfs/assets/1554520/a5ff15b4-c10a-4472-8c03-1604c69d976a)

(the process continues after the screenshot ends...)

**Additional context**

**Comment by asabya** [comment]
Upload dir does not require trailing `*` for uploading all content. Just specify the dir to upload thats it.
