### ISSUE TITLE
Pod creation is not accessible / can be imported in webapp but gateway has access

### ISSUE THREAD

**Issue by tamas6** [fairDataSociety/fairOS-dfs#528]
[#403
](https://github.com/fairDataSociety/fairdrive-theapp/issues/403#issue-1814342832)

**To Reproduce**
upload to a pod through fairOS-cli, and check if it's accessible from the webapp

**Screenshots**

![IMAGE 2023-07-20 17:58:21](https://github.com/fairDataSociety/fairOS-dfs/assets/81620050/1f0049fb-6ef8-46da-a0d8-8a4dd871d551)
![IMAGE 2023-07-20 17:58:23](https://github.com/fairDataSociety/fairOS-dfs/assets/81620050/c3956ee5-a95b-4444-95cd-5d01de27d300)
![IMAGE 2023-07-20 18:08:48](https://github.com/fairDataSociety/fairOS-dfs/assets/81620050/e4ae5559-3fda-4ae6-9c2a-57ebc2ee6314)

**Comment by asabya** [comment]
Seems a webapp issue to me. Please close this if it gets resolved. @tamas6
