### ISSUE TITLE
Dfs-cli terminate requiring user password with Windows

### ISSUE THREAD

**Issue by tmm360** [fairDataSociety/fairOS-dfs#53]
**Describe the bug**
Using dfs-cli with Windows, when the user password is requested the application terminate.

**To Reproduce**
1. Compile for Windows
2. Execute `dfs-cli-windows-amd64.exe`
3. `user new sameUsername`

**Expected behavior**
It should receive user password and don't terminate.

**Comment by asabya** [comment]
This should not happen anymore. Please feel free to reopen if it still persists
