### ISSUE TITLE
error while running fairOs node

### ISSUE THREAD

**Issue by Amanb1145** [fairDataSociety/fairOS-dfs#532]
Hey,
my bee version is- 
Tried running this repo with both docker and manually but neither worked-
1- docker-1.16.1-8e269c88
followed this guide- https://docs.fairos.fairdatasociety.org/docs/fairOS-dfs/fairos-dfs-using-docker
error-
`sudo docker run  -p 9090:9090   --rm -it fairdatasociety/fairos-dfs  server     --ens-network="testnet"     --rpc="https://xdai.dev.fairdatasociety.org"     --beeApi="http://localhost:1633"     --postageBlockId=eaccebfc6bcdb4035520672152ca80c1bada266fasec9f5fac99421693283f7d89b`
error-
```
ERRO[2023-08-08T23:55:25Z] dfs: ens initialisation failed chainID does not match or not supported 
ERRO[2023-08-08T23:55:25Z] chainID does not match or not supported 
```
2- Manual-
I also tried- cloning- https://github.com/fairDataSociety/fairOS-dfs
and followed this-https://docs.fairos.fairdatasociety.org/docs/fairOS-dfs/manual-installation
git clone https://github.com/fairDataSociety/fairOS-dfs.git
cd fairOS-dfs
make binary
./dist/dfs server --postageBlockId "RECEIVED_BATCH_ID" #(starts FairOS-dfs in server mode)
./dist/dfs-cli #(starts the FairOS-dfs client)
It does not work either

Thanks

update-
tried this also-
`sudo docker run  -p 9090:9090   --rm -it fairdatasociety/fairos-dfs  server     --ens-network="testnet"     --rpc="https://sepolia.dev.fairdatasociety.org"     --beeApi="http://localhost:1633"     --postageBlockId=eaccebfc6bcdb4035520672152ca80c1bada266fasec9f5fac99421693283f7d89b`
does not  work

**Comment by asabya** [comment]
@Amanb1145 Are you running bee in docker?

**Comment by Amanb1145** [comment]
Hey @asabya 
I installed bee using - 
  417  wget https://github.com/ethersphere/bee/releases/download/v1.16.1/bee_1.16.1_amd64.deb
  418  sudo dpkg -i bee_1.16.1_amd64.deb

**Comment by Amanb1145** [comment]
I think it does not work with localhost even on same server I tried running it using a proxy and it worked 
Thanks
