### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairOS-dfs#545]
Run tests on actual bee. 

- Download bee in the action
- Run `bee dev`
- Buy stamp
- Use stamp to init blockstore

**Comment by asabya** [comment]
`operation not supported in dev mode` while POSTing on /soc/

**Comment by tfius** [comment]
eh

**Comment by asabya** [comment]
running a bee server based on this test https://github.com/ethersphere/bee/blob/759f56f7d71a76edcfb3122ef044490306d4e6b6/pkg/api/api_test.go#L135
