### ISSUE TITLE
billions of pods per wallet

### ISSUE THREAD

**Issue by rezahsnz** [fairDataSociety/fairOS-dfs#554]
Processes need smol pods to put their outputs. Right now, one can only create 30s of pods and this limitations is no good.

**Comment by crtahlin** [comment]
Related to https://github.com/fairDataSociety/fdp-storage/issues/290

**Comment by asabya** [comment]
Although billion is possible. Everything will be really laggy. But lets stick to "Hundreds" for now with https://github.com/fairDataSociety/fairOS-dfs/releases/tag/v0.10.0-rc5
