### ISSUE TITLE
Wasm fails to load

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairOS-dfs#561]
**Describe the bug**
unable to load wasm, built with go1.21

**Expected behavior**
should be able to load wasm

**Screenshots**
![image](https://github.com/fairDataSociety/fairOS-dfs/assets/15252513/97e0768c-905f-48ad-8739-15a2d4cd1d7e)

**Comment by asabya** [comment]
updating the `wasm_exec.js` file to the latest will solve this issue

**Comment by tfius** [comment]
Do we keep wasm_exec.js with corresponding .wasm in releases ?

**Comment by asabya** [comment]
> Do we keep wasm_exec.js with corresponding .wasm in releases ?

Added in https://github.com/fairDataSociety/fairOS-dfs/releases/tag/v0.10.0-rc5

We should share the link from go repo directly
