### ISSUE TITLE
Use stateless REST api

### ISSUE THREAD

**Issue by tmm360** [fairDataSociety/fairOS-dfs#59]
**Is your feature request related to a problem? Please describe.**
Currently APIs require specific order of actions from the clients, for example for interact with pods is necessary to open first them. This implies to have a state with rest api, that is an anti-pattern.

Eventual state has to be maintained only client side, keeping free as possibile apis from these logic. For the specific sample, interaction with a pod should only require to pass with a request the identifier of the destination pod.

**Describe the solution you'd like**
Remove any state-related logic from apis. The only allowed state is the user authentication keeped with cookie.

**Comment by Xerosigma** [comment]
Cookies may not make sense in many decentralized situations. If everything is running locally a lot of your typical browser security protocols become unnecessary.

**Comment by asabya** [comment]
with [v0.9.3](https://github.com/fairDataSociety/fairOS-dfs/releases/tag/v0.9.3) we no longer need to call pod/open to maintain state flow.
