### ISSUE TITLE
Shell process doesnt exit clean in WSL2

### ISSUE THREAD

**Issue by rampall** [fairDataSociety/fairOS-dfs#593]
**Describe the bug**
In WSL2 shell i am unable to type anything when i exit the dfs-cli session,  Not sure if this is the case in other setups.
![image](https://github.com/fairDataSociety/fairOS-dfs/assets/520570/0787b95a-289e-483e-8a4d-4f9d5ce486e5)

**Comment by asabya** [comment]
@rampall Can you please try https://github.com/fairDataSociety/fairOS-dfs/releases/tag/v0.10.0-rc7 dfs-cli to check if this still persists?

**Comment by asabya** [comment]
@rampall closing this. Please feel free to reopen if the issue persists

**Comment by rampall** [comment]
@asabya  Unfortunately, the problem still persists ...
![image](https://github.com/fairDataSociety/fairOS-dfs/assets/520570/2aeb2ea8-4f63-4eb6-bca1-2319a28c2382)
