### ISSUE TITLE
Move tests to pkg_test

### ISSUE THREAD

**Issue by jmozah** [fairDataSociety/fairOS-dfs#6]
**Describe the cleanup task**
All the test files are in the same package as the production code.
They need to be moved to package_test 

**Screenshots**
- None

**Additional context**
- None

**Comment by crtahlin** [comment]
@tfius is this relevant to do or should it be closed?

**Comment by asabya** [comment]
> @tfius is this relevant to do or should it be closed?

There are some packages in fairOS-dfs that are `*_test` which can be moved to `package_test`. I do not think this is required right now. We can implement this if needed in future.

**Comment by asabya** [comment]
most of the tests have been moved to `_test` package
