### ISSUE TITLE
Add support for erasure coding

### ISSUE THREAD

**Issue by asabya** [fairDataSociety/fairOS-dfs#615]
Bee v2 introdues erasure coding with `swarm-redundancy-level` header.

We add this in the config and use it in `/bytes` and `/bzz` endpoints

**Comment by crtahlin** [comment]
Is this done? How can a user set erasure coding for uploading, using the server and CLI combination.

**Comment by asabya** [comment]
its already done.

https://github.com/fairDataSociety/fairOS-dfs/issues/613#issuecomment-2109520188
