### ISSUE TITLE
can not creat new user

### ISSUE THREAD

**Issue by flybobdog** [fairDataSociety/fairOS-dfs#68]
server log:
INFO[2021-06-29T13:59:30+08:00] configuration values                         
INFO[2021-06-29T13:59:30+08:00] version      : 0.5.0-c78c8d1                 
INFO[2021-06-29T13:59:30+08:00] dataDir      : /root/.fairOS/dfs             
INFO[2021-06-29T13:59:30+08:00] beeHost      : 127.0.0.1                     
INFO[2021-06-29T13:59:30+08:00] beePort      : 1633                          
INFO[2021-06-29T13:59:30+08:00] verbosity    : 5                             
INFO[2021-06-29T13:59:30+08:00] httpPort     : 9090                          
INFO[2021-06-29T13:59:30+08:00] pprofPort    : 9091                          
INFO[2021-06-29T13:59:30+08:00] cookieDomain : api.fairos.io                 
INFO[2021-06-29T13:59:30+08:00] corsOrigins  : []                            
INFO[2021-06-29T13:59:30+08:00] fairOS-dfs API server listening on port: 9090 
INFO[2021-06-29T13:59:30+08:00] fairOS-dfs pprof listening on port: 9091     
ERRO[2021-06-29T14:00:07+08:00] user login: no feed updates found            
INFO[2021-06-29T14:00:07+08:00] api access                                    duration=0.103209544 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=60 status=500 uri=/v0/user/login user-agent=Go-http-client/1.1

ERRO[2021-06-29T14:00:16+08:00] user signup: error uploading data            
INFO[2021-06-29T14:00:16+08:00] api access                                    duration=0.032003651 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=60 status=500 uri=/v0/user/signup user-agent=Go-http-client/1.1

create user:  user signup: error uploading data
successfully connect to swarm testnet .

**Comment by IgorShadurin** [comment]
What the bee version?

**Comment by IgorShadurin** [comment]
Reproduced with 
dfs: 0.5.3-5dbb5fe-dirty
and
bee: 1.0

**Comment by asabya** [comment]
Not reproducible in latest version
