### ISSUE TITLE
Batch actions

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#71]
For web applications it would be great to group and execute some commands to speedup data processing and improving user experience.
In some cases web app should execute several commands to make one logical action. 
For example. To store one param in key-value storage web app should execute 5 commands: pod create, pod open, kv create, kv open, kv put kv. 
5 http requests for one simple action is not good idea due to speed reason. I think fairOS could accept list of commands in one request.

**Comment by asabya** [comment]
This can be done with the new websocket implementation without calling multiple http calls @IgorShadurin

**Comment by asabya** [comment]
@IgorShadurin does fdp-storage has plans for this? 
We can have this is a way where, To store one param in key-value storage if the user passes `password` as argument then we will check if pod exists, if the pod is open, if kv tabel exists, if kv table open, then do whatever is required and put the mv.

**Comment by IgorShadurin** [comment]
> @IgorShadurin does fdp-storage has plans for this? We can have this is a way where, To store one param in key-value storage if the user passes `password` as argument then we will check if pod exists, if the pod is open, if kv tabel exists, if kv table open, then do whatever is required and put the mv.

We have no plans for this. The idea was to somehow speed up the upload of key-value data (thousands of OSM tiles, for example). But now I'm not sure that the proposed option is the solution.
