### ISSUE TITLE
Store shared pod to custom directory

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#74]
User 1: Created pod "hello", make shared reference, share it with User 2.
User 2: Early created pod "hello" for his purposes, trying to receive shared pod by reference, get conflict due to pod name.

Add possibility for API to copy shared pod to "folder" with other name.

**Comment by asabya** [comment]
- For pod share, we add a query param `shared_pod_name`.
- For receiving pod, we also add a query param parameter to save the pod  `shared_pod_name`
