### ISSUE TITLE
SOC Problem - When having two pods for a user will cause issue for second pod

### ISSUE THREAD

**Issue by mmahmutovic** [fairDataSociety/fairOS-dfs#75]
**Describe the bug**
When user creates second pod, user cannot create new files or directory. For files it says directory is not present, when uploading it to root directory. When creating new directory error is  "no new feed updates" 

**To Reproduce**
1. Create new pod
2. Open the pod
3. Create new file/Folder

**Expected behavior**
After uploading file, it should appear on pod. Same goes to directory

**Screenshots**

**Additional context**

**Comment by crtahlin** [comment]
I think this might be a bug, @jmozah ?
