### ISSUE TITLE
Incorrect behaviour for uploading

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#83]
1) Login with existing user
2) Create new pod
3) Upload file (cmd or api)

Error message: "Directory not present".
<img width="519" alt="Screenshot 2021-07-23 at 11 12 49" src="https://user-images.githubusercontent.com/1595061/126754695-b6e7e759-be26-4b4e-8974-7af4e405383a.png">

Confirmed at 3d50e30 by API with message: `Responses: [ { file_name: 'hello.txt', message: 'directory not present' } ]`

Workaround: relogin after every action that make changes. Then it works.

**Comment by asabya** [comment]
Got fixed in https://github.com/fairDataSociety/fairOS-dfs/releases/tag/v0.7.2
