### ISSUE TITLE
Import user with only address

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#90]
In documentation defined 2 commands for importing user:

```
POST -F 'user=\<username>' -F 'address=\<user_address>' -F 'password=\<password>' http://localhost:9090/v0/user/import
POST -F 'user=\<username>' -F 'mnemonic=\<12_word_mnemonic>' -F 'password=\<password>' http://localhost:9090/v0/user/import
```

Second command with mnemonic phrase works well.
First command throw error 500, "Internal Server Error".

Should this command work only with an address and without a mnemonic?

**Comment by tfius** [comment]
How can one Import account with adress only?
One could Import account with private key

**Comment by asabya** [comment]
with new account registration system in v0.8.0 we no longer have the import feature available.
