### ISSUE TITLE
kv/count incorrect response structure

### ISSUE THREAD

**Issue by IgorShadurin** [fairDataSociety/fairOS-dfs#92]
Request `kv/count` via API.
Response: `{ message: 'kv store my_test_kv has 0 records', code: 200 }`

Expected: records count should be returned like json field, example `{ count: 0, code: 200 }`

**Comment by tfius** [comment]
hmm, can you add also a field `name:"my_test_kv`

**Comment by asabya** [comment]
`table_name` field added. Response looks like this
```
{
    "count": 4,
    "table_name": "tea"
}
```
